// ─────────────────────────────────────────────
// Auth error codes
// ─────────────────────────────────────────────
export const AUTH_ERRORS = {
  // Request validation
  INVALID_REQUEST: `INVALID_REQUEST`,
  INVALID_EMAIL: `INVALID_EMAIL`,
  INVALID_PASSWORD: `INVALID_PASSWORD`,

  // Credentials / OTP
  INVALID_CREDENTIALS: `INVALID_CREDENTIALS`,
  INVALID_OTP: `INVALID_OTP`,
  INVALID_STATE: `INVALID_STATE`,

  // Account state
  ACCOUNT_DEACTIVATED: `ACCOUNT_DEACTIVATED`,
  EMAIL_NOT_VERIFIED: `EMAIL_NOT_VERIFIED`,
  UNAUTHORIZED: `UNAUTHORIZED`,
  FORBIDDEN: `FORBIDDEN`,

  // Conflicts
  EMAIL_CONFLICT: `EMAIL_CONFLICT`,
  USER_EXISTS: `USER_EXISTS`,
  MISSING_EMAIL: `MISSING_EMAIL`,
  NO_ACCOUNT: `NO_ACCOUNT`,

  // Session / token
  NO_TOKEN: `NO_TOKEN`,
  TOKEN_INVALID: `TOKEN_INVALID`,
  FRESH_AUTH_REQUIRED: `FRESH_AUTH_REQUIRED`,

  // Server failures
  SIGNUP_FAILED: `SIGNUP_FAILED`,
  AUTO_LOGIN_FAILED: `AUTO_LOGIN_FAILED`,
  NO_AUTH_ID: `NO_AUTH_ID`,
  RESEND_FAILED: `RESEND_FAILED`,
};
